# Generated by Django 4.2.3 on 2023-07-31 21:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="EC"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(max_length=100, verbose_name="Url de facebook"),
                ),
                (
                    "instagram",
                    models.URLField(max_length=100, verbose_name="Url de instagram"),
                ),
                (
                    "tiktok",
                    models.URLField(max_length=100, verbose_name="Url de tiktok"),
                ),
                (
                    "whatsapp",
                    models.URLField(blank=True, verbose_name="Url de whatsapp"),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Titulo")),
                ("content", models.TextField(max_length=50, verbose_name="Contenido")),
            ],
            options={
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
            },
        ),
    ]
