# Generated by Django 4.2.4 on 2023-08-24 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="created",
        ),
        migrations.RemoveField(
            model_name="news",
            name="modified",
        ),
        migrations.AddField(
            model_name="news",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Fecha de publicacion",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(max_length=130, verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Titulo"),
        ),
    ]
