# Generated by Django 4.2.7 on 2024-02-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Url de facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Url de instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tiktok',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Url de tiktok'),
        ),
    ]
