# Generated by Django 4.2.4 on 2023-08-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_news_created_remove_news_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="andress",
            field=models.TextField(default="perro", verbose_name="Dirección"),
            preserve_default=False,
        ),
    ]
