# Generated by Django 4.2.4 on 2023-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_contact_andress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="andress",
            field=models.TextField(max_length=350, verbose_name="Dirección"),
        ),
    ]
