# Generated by Django 4.2.7 on 2023-12-09 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Nombre del del descuento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('state', model_utils.fields.StatusField(choices=[('Valido', 'Valido'), ('Invalido', 'Invalido')], default='Valido', max_length=100, no_check_for_status=True)),
                ('inicio', models.DateField(default=django.utils.timezone.now)),
                ('final', models.DateField(default=datetime.datetime(2023, 12, 19, 1, 53, 55, 490587, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del plan')),
                ('description', models.TextField(max_length=225, verbose_name='Descripcion del plan')),
                ('instrument', models.SmallIntegerField(choices=[(1, 'Piano'), (2, 'Canto'), (3, 'Guitarra'), (4, 'Batería'), (5, 'Violin'), (6, 'Bajo')])),
                ('modality', model_utils.fields.StatusField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Curso', 'Curso')], default='Online', max_length=100, no_check_for_status=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='plans.discount')),
            ],
            options={
                'verbose_name': 'Plan de estudio',
                'verbose_name_plural': 'Planes de estudio',
            },
        ),
    ]
