# Generated by Django 4.2.7 on 2023-12-27 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2024, 1, 6, 16, 52, 57, 749164, tzinfo=datetime.timezone.utc)),
        ),
    ]
