# Generated by Django 4.2.3 on 2023-07-31 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 10, 21, 25, 40, 431208, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
