# Generated by Django 4.2.7 on 2024-02-20 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_discount_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 18, 19, 27, 967976, tzinfo=datetime.timezone.utc)),
        ),
    ]
