# Generated by Django 4.2.4 on 2023-11-12 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_discount_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 3, 37, 56, 59967, tzinfo=datetime.timezone.utc)),
        ),
    ]
