# Generated by Django 4.2.3 on 2023-07-31 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 10, 23, 53, 25, 933019, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
