# Generated by Django 4.2.3 on 2023-08-01 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0004_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 11, 3, 3, 18, 290805, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
