# Generated by Django 4.2.7 on 2024-02-24 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_discount_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2024, 3, 5, 0, 15, 26, 681072, tzinfo=datetime.timezone.utc)),
        ),
    ]
