# Generated by Django 4.2.3 on 2023-08-02 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 12, 2, 37, 36, 568462, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
