# Generated by Django 4.2.7 on 2024-02-24 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_discount_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2024, 3, 5, 7, 13, 20, 368307, tzinfo=datetime.timezone.utc)),
        ),
    ]
