# Generated by Django 4.2.7 on 2024-02-24 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_discount_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2024, 3, 5, 13, 55, 40, 395306, tzinfo=datetime.timezone.utc)),
        ),
    ]
