# Generated by Django 4.2.4 on 2023-08-13 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0006_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 23, 3, 39, 27, 366778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
