# Generated by Django 4.2.4 on 2023-11-14 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_discount_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='final',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 1, 23, 0, 113630, tzinfo=datetime.timezone.utc)),
        ),
    ]
