# Generated by Django 4.2.4 on 2023-08-23 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0007_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 2, 4, 46, 6, 748031, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="instrument",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Piano"),
                    (2, "Canto"),
                    (3, "Guitarra"),
                    (4, "Batería"),
                    (5, "Violin"),
                    (6, "Bajo"),
                ]
            ),
        ),
    ]
