# Generated by Django 4.2.4 on 2023-08-24 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0009_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 3, 18, 42, 31, 768323, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
