# Generated by Django 4.2.4 on 2023-08-24 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0011_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 3, 18, 45, 0, 46989, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
