# Generated by Django 4.2.4 on 2023-08-25 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0012_alter_discount_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="final",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 4, 2, 34, 13, 434311, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(max_length=225, verbose_name="Descripcion del plan"),
        ),
    ]
