# Generated by Django 4.2.4 on 2023-11-03 20:31

import applications.gallery.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('image', models.ImageField(upload_to=applications.gallery.models.custom_image_name)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Fecha de publicacion')),
                ('public', models.BooleanField(default=False, verbose_name='Publico')),
                ('principal', models.BooleanField(default=False, verbose_name='Visible en la pantalla principal')),
                ('category', models.ManyToManyField(related_name='Imagenes', to='gallery.category')),
            ],
        ),
    ]
