# Generated by Django 4.2.3 on 2023-08-01 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de publicacion",
                    ),
                ),
                ("public", models.BooleanField(default=False, verbose_name="Publico")),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="Visible en la pantalla principal"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="Imagenes", to="gallery.category"
                    ),
                ),
            ],
        ),
    ]
