# Generated by Django 4.2.3 on 2023-08-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="titulo",
            field=models.CharField(default="el pato gay"),
            preserve_default=False,
        ),
    ]
