# Generated by Django 4.2.4 on 2023-11-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
    ]
