# Generated by Django 4.2.4 on 2023-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
