# Generated by Django 4.2.4 on 2023-08-13 03:39

import applications.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_image_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to=applications.gallery.models.custom_image_name
            ),
        ),
    ]
