# Generated by Django 4.2.4 on 2023-11-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
